### PR TITLE
[Bref] Add layer name

### PR DESCRIPTION
**Pull request by Nyholm**
This will be supported in Bref 1.3

See https://github.com/brefphp/bref/pull/1031

### CODE REVIEW

**Comment by Nyholm** [comment]
FYI @deleugpn

**Comment by deleugpn** [comment]
@mnapoli since you're the one who will be looking at the stats on CloudWatch.

**Comment by mnapoli** [comment]
Thanks for the ping. Could it be possible to put `symfony` in the name? (e.g. `symfony-runtime` and `symfony-runtime-console`) That will make recognizing the metrics easier, because just `runtime` is very generic.

**Comment by Nyholm** [comment]
Of course. I wasn't sure if we could use hyphens `-`

**Pull request merged**
