### PR TITLE
Psr http message

### PR DESCRIPTION
**Pull request by Nyholm**
@thecaliskan can you verify if this works for you?

### CODE REVIEW

**Comment by thecaliskan** [comment]
https://github.com/php-runtime/roadrunner-symfony-nyholm/pull/3

**Comment by thecaliskan** [comment]
it should be like this because it needs to be compatible with older versions.

`"symfony/psr-http-message-bridge": "^2.1 || ^6.0 || ^7.0",`

image

**Comment by thecaliskan** [comment]
Thanks @Nyholm

**Comment by Nyholm** [comment]
The PR is merged. Are you able to install dev-main?

**Comment by thecaliskan** [comment]
It works. You can release a new version. Thanks!


```bash
composer require runtime/roadrunner-symfony-nyholm --no-cache
./composer.json has been updated
Running composer update runtime/roadrunner-symfony-nyholm
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "7.0.*"
Updating dependencies
Lock file operations: 16 installs, 0 updates, 0 removals
  - Locking composer/semver (dev-main 1d09200)
  - Locking nyholm/psr7 (dev-master fd12ffc)
  - Locking psr/http-factory (dev-master 7037f4b)
  - Locking psr/http-message (1.1)
  - Locking runtime/roadrunner-symfony-nyholm (dev-main 1e2e2db)
  - Locking spiral/core (dev-master b34d72c)
  - Locking spiral/goridge (3.x-dev d5303e6)
  - Locking spiral/logger (dev-master e4927aa)
  - Locking spiral/roadrunner (v2.12.3)
  - Locking spiral/roadrunner-cli (2.x-dev a896e1d)
  - Locking spiral/roadrunner-http (2.x-dev 2520f41)
  - Locking spiral/roadrunner-worker (2.x-dev 2c58986)
  - Locking spiral/tokenizer (dev-master 0918595)
  - Locking symfony/http-client (7.0.x-dev db71498)
  - Locking symfony/http-client-contracts (dev-main 8a3631b)
  - Locking symfony/psr-http-message-bridge (7.0.x-dev c5e9730)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 16 installs, 0 updates, 0 removals
  - Downloading psr/http-message (1.1)
  - Downloading symfony/psr-http-message-bridge (7.0.x-dev c5e9730)
  - Downloading spiral/goridge (3.x-dev d5303e6)
  - Downloading spiral/roadrunner-worker (2.x-dev 2c58986)
  - Downloading psr/http-factory (dev-master 7037f4b)
  - Downloading spiral/roadrunner-http (2.x-dev 2520f41)
  - Downloading symfony/http-client-contracts (dev-main 8a3631b)
  - Downloading symfony/http-client (7.0.x-dev db71498)
  - Downloading spiral/core (dev-master b34d72c)
  - Downloading spiral/logger (dev-master e4927aa)
  - Downloading spiral/tokenizer (dev-master 0918595)
  - Downloading composer/semver (dev-main 1d09200)
  - Downloading spiral/roadrunner-cli (2.x-dev a896e1d)
  - Downloading nyholm/psr7 (dev-master fd12ffc)
  - Downloading runtime/roadrunner-symfony-nyholm (dev-main 1e2e2db)
  - Installing psr/http-message (1.1): Extracting archive
  - Installing symfony/psr-http-message-bridge (7.0.x-dev c5e9730): Extracting archive
  - Installing spiral/goridge (3.x-dev d5303e6): Extracting archive
  - Installing spiral/roadrunner-worker (2.x-dev 2c58986): Extracting archive
  - Installing psr/http-factory (dev-master 7037f4b): Extracting archive
  - Installing spiral/roadrunner-http (2.x-dev 2520f41): Extracting archive
  - Installing symfony/http-client-contracts (dev-main 8a3631b): Extracting archive
  - Installing symfony/http-client (7.0.x-dev db71498): Extracting archive
  - Installing spiral/core (dev-master b34d72c): Extracting archive
  - Installing spiral/logger (dev-master e4927aa): Extracting archive
  - Installing spiral/tokenizer (dev-master 0918595): Extracting archive
  - Installing composer/semver (dev-main 1d09200): Extracting archive
  - Installing spiral/roadrunner-cli (2.x-dev a896e1d): Extracting archive
  - Installing spiral/roadrunner (v2.12.3)
  - Installing nyholm/psr7 (dev-master fd12ffc): Extracting archive
  - Installing runtime/roadrunner-symfony-nyholm (dev-main 1e2e2db): Extracting archive
Generating autoload files
41 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (925c93876f9735ecd7fd4245d9e13da2)
  - Configuring nyholm/psr7 (>=1.0): From github.com/symfony/recipes:main
Executing script cache:clear [OK]
Executing script assets:install public [OK]
              
 What's next? 
              

Some files have been created and/or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

No security vulnerability advisories found.
Using version dev-main for runtime/roadrunner-symfony-nyholm
```

**Comment by thecaliskan** [comment]
When I changed to the stable version, I getting the following error. @Nyholm 
 
 
 ``` bash
 composer require runtime/roadrunner-symfony-nyholm --no-cache
./composer.json has been updated
Running composer update runtime/roadrunner-symfony-nyholm
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - runtime/roadrunner-symfony-nyholm[0.1.0, ..., 0.3.1] require nyholm/psr7 ^1.4 -> nyholm/psr7 is fixed to 1.8.x-dev (lock file version) by a partial update but that version is rejected by your minimum-stability. Make sure you list it as an argument for the update command.
    - Root composer.json requires runtime/roadrunner-symfony-nyholm * -> satisfiable by runtime/roadrunner-symfony-nyholm[0.1.0, ..., 0.3.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require runtime/roadrunner-symfony-nyholm:*" to figure out if any version is installable, or "composer require runtime/roadrunner-symfony-nyholm:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Pull request merged**
