### PR TITLE
feat(road-runner): allow ^2023.1.0 and ^2.0

### PR DESCRIPTION
**Pull request by alexander-schranz**
See #138 /cc @gsdevme

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Looks currently there is a dependency to symfony/console missing not sure if we should add it to require or require-dev as the dependency is not defined by `symfony/runtime` class where it is used. @Nyholm what do you think?

**Comment by gsdevme** [comment]
Yeah its needed in `require-dev`, I cant push the change though on this branch @alexander-schranz

**Comment by alexander-schranz** [comment]
@gsdevme you can just open another PR with the required require-dev to the symfony/console.

**Comment by alexander-schranz** [comment]
The `spiral/roadrunner` package seems not longer provide any PHP code since there version changes. The change is https://github.com/roadrunner-server/roadrunner/commit/8d316e575e8e72f38e9f2e8f587f5bf7a006ef95

Maybe @roxblnfk can help us out what packages we should require here. From first look at I would see we require `roadrunner-php/worker` `^2 || ^3`.

**Comment by roxblnfk** [comment]
Hi @alexander-schranz ✋
Add `spiral/roadrunner` only if you are directly tied to any features of the RoadRunner server.

In the code of this package, classes from the following are used directly:
- [`spiral/roadrunner-http`](https://packagist.org/packages/spiral/roadrunner-http)
- [`spiral/roadrunner-worker`](https://packagist.org/packages/spiral/roadrunner-worker)

The [`spiral/roadrunner-cli`](https://packagist.org/packages/spiral/roadrunner-cli) is helpful to load RoadRunner server binary files.

I recommend using the latest versions of the mentioned packages. However, you can try a wider range of versions, excluding `spiral/roadrunner`:

```
spiral/roadrunner-http: ^2 || ^3.2
spiral/roadrunner-worker: ^2 || ^3
spiral/roadrunner-cli: ^2
```

**Comment by alexander-schranz** [comment]
Thx @roxblnfk, think in our case it does make sense to go with:

```
spiral/roadrunner-http: ^2 || ^3.2
spiral/roadrunner-worker: ^2 || ^3
spiral/roadrunner-cli: ^2
```

which was also the previous packages which where installed when using `"spiral/roadrunner": "^2.0"`. 

@Nyholm are you fine with that?

**Comment by Nyholm** [comment]
Yepp. I think that makes sense. Thank you

**Comment by davidPaymefy** [comment]
Hi, do we know when this is going to be available? spiral/roadrunner is already on version 2024

**Comment by davidPaymefy** [comment]
> Hi, do we know when this is going to be available? spiral/roadrunner is already on version 2024

https://github.com/php-runtime/runtime/pull/172

**Comment by alexander-schranz** [comment]
close in favor of #172

**Pull request closed without merging**
