### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by chalasr**

### CODE REVIEW

**Comment by jeremyFreeAgent** [comment]
Thanks!

**Comment by Nyholm** [comment]
Lovely. Thank you

**Comment by Nyholm** [comment]
No, not really. Let's release it now. 
What packages are you interested in?

**Comment by Chris53897** [comment]
That would be great. 
frankenphp

https://github.com/dunglas/frankenphp-demo/pull/17

**Comment by Nyholm** [comment]
Release is in the works. Stay tuned.

**Pull request merged**
